services:
  pythonapp:
    build: ./
    command: sh -c "sleep 10s ; python3 ./main.py"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nh@n18082002
      MYSQL_DATABASE: sqldocker
      MYSQL_USER: root
      MYSQL_PASSWORD: Nh@n18082002
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql